### ISSUE TITLE
Intellisense works for Express 3 but not Express 4

### ISSUE THREAD

**Issue by HolisticDeveloper** [Microsoft/nodejstools#631]
I'm relatively new to node and NTVS. I'm trying to figure out whether or not some intellisense behavior I am seeing is expected.

I'm using:
- VS 2015 Enterprise RTM
- NTVS 1.1
- various other extensions (Resharper is installed but disabled)

If I have some simple code like so:

```
var express = require('express');
var app = express();
```

I can get statement completion for `app.get` when using express 3.21.2 but not when using express 4.13.3. With express 4.13.3, the statement completion options for `app.get` are as follows:
```
arguments
__defineGetter__
__lookupGetter__
```

Note: my primary goal is actually to get intellisense for the [twilio](https://github.com/twilio/twilio-node/) package, but I noticed I had the same/similar problem for express and I figured people might be more familiar with that.

**Comment by billti** [comment]
Are you running the final Node Tools 1.1 release? I believe we fixed pretty much this issue in https://github.com/Microsoft/nodejstools/issues/566 before the final release.

**Comment by HolisticDeveloper** [comment]
Yes, I'm running the final 1.1 release. I checked just now and found I had the 1.1 RC for VS 2013 (using VS 2015) in this case, so I went ahead and tried uninstalling all versions and reinstalling, but the issue persists.

If I hover over 'app' in the second line, I do get the following intellisense:
```
app: function app(req, res, next)
```

but still no statement completion.

**Comment by HolisticDeveloper** [comment]
@mousetraps You tagged this as "need-more-info" -- what else can I provide?

**Comment by mjbvz** [comment]
Sorry there for the lack of follow up on this. I'm closing the issue only because the current status of the issue is unclear and I want to make sure we are tracking actionable issues. If you are still running into this issue, please let me know and we will reopen this and continue the investigation. 

Additionally, you can try using the NTVS 1.2 alpha with ES6 Preview intellisense to see if that improves things. That is the modern intellisense experience we are moving towards. It can provide richer intellisense for packages like Express, while also being more reliable.
